spring:
  application:
    name: springcloud-consumer
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        healthCheckPath: /consumerhealth
        healthCheckInterval: 15s
server:
  port: 8080